sudo: false
language: python
python:
  - "3.5"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=docs
  - TOX_ENV=py27-flake8
  - TOX_ENV=py35-flake8

install:
   - pip install tox

script:
   - tox -e $TOX_ENV
